#############################################################################
# Makefile for building: Third
# Generated by qmake (2.01a) (Qt 4.6.0) on: ?? 3? 2 14:47:17 2017
# Project:  Third.pro
# Template: app
# Command: /opt/qtsdk-2009.05/qt/bin/qmake -spec /opt/qtsdk-2009.05/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile Third.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/qtsdk-2009.05/qt/mkspecs/linux-g++ -I. -I/opt/qtsdk-2009.05/qt/include/QtCore -I/opt/qtsdk-2009.05/qt/include/QtGui -I/opt/qtsdk-2009.05/qt/include/QtSql -I/opt/qtsdk-2009.05/qt/include -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/qtsdk-2009.05/qt/lib
LIBS          = $(SUBLIBS)  -L/opt/qtsdk-2009.05/qt/lib -lQtSql -L/opt/qtsdk-2009.05/qt/lib -lQtGui -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/qtsdk-2009.05/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mywidget1.cpp \
		mywidget2.cpp \
		mywidget.cpp \
		mydialog.cpp \
		mainview.cpp \
		tempview.cpp moc_mywidget.cpp \
		moc_mywidget1.cpp \
		moc_mywidget2.cpp \
		moc_mydialog.cpp \
		moc_mainview.cpp
OBJECTS       = main.o \
		mywidget1.o \
		mywidget2.o \
		mywidget.o \
		mydialog.o \
		mainview.o \
		tempview.o \
		moc_mywidget.o \
		moc_mywidget1.o \
		moc_mywidget2.o \
		moc_mydialog.o \
		moc_mainview.o
DIST          = /opt/qtsdk-2009.05/qt/mkspecs/common/g++.conf \
		/opt/qtsdk-2009.05/qt/mkspecs/common/unix.conf \
		/opt/qtsdk-2009.05/qt/mkspecs/common/linux.conf \
		/opt/qtsdk-2009.05/qt/mkspecs/qconfig.pri \
		/opt/qtsdk-2009.05/qt/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/qt_config.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/default_pre.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/debug.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/default_post.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/warn_on.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/qt.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/moc.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/resources.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/uic.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/yacc.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/lex.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/include_source_dir.prf \
		Third.pro
QMAKE_TARGET  = Third
DESTDIR       = 
TARGET        = Third

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Third.pro  /opt/qtsdk-2009.05/qt/mkspecs/linux-g++/qmake.conf /opt/qtsdk-2009.05/qt/mkspecs/common/g++.conf \
		/opt/qtsdk-2009.05/qt/mkspecs/common/unix.conf \
		/opt/qtsdk-2009.05/qt/mkspecs/common/linux.conf \
		/opt/qtsdk-2009.05/qt/mkspecs/qconfig.pri \
		/opt/qtsdk-2009.05/qt/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/qt_config.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/default_pre.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/debug.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/default_post.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/warn_on.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/qt.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/moc.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/resources.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/uic.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/yacc.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/lex.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/include_source_dir.prf \
		/opt/qtsdk-2009.05/qt/lib/libQtSql.prl \
		/opt/qtsdk-2009.05/qt/lib/libQtCore.prl \
		/opt/qtsdk-2009.05/qt/lib/libQtGui.prl
	$(QMAKE) -spec /opt/qtsdk-2009.05/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile Third.pro
/opt/qtsdk-2009.05/qt/mkspecs/common/g++.conf:
/opt/qtsdk-2009.05/qt/mkspecs/common/unix.conf:
/opt/qtsdk-2009.05/qt/mkspecs/common/linux.conf:
/opt/qtsdk-2009.05/qt/mkspecs/qconfig.pri:
/opt/qtsdk-2009.05/qt/mkspecs/features/qt_functions.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/qt_config.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/exclusive_builds.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/default_pre.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/debug.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/default_post.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/warn_on.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/qt.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/unix/thread.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/moc.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/resources.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/uic.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/yacc.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/lex.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/include_source_dir.prf:
/opt/qtsdk-2009.05/qt/lib/libQtSql.prl:
/opt/qtsdk-2009.05/qt/lib/libQtCore.prl:
/opt/qtsdk-2009.05/qt/lib/libQtGui.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/qtsdk-2009.05/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile Third.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Third1.0.0 || $(MKDIR) .tmp/Third1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Third1.0.0/ && $(COPY_FILE) --parents mywidget.h mywidget1.h mywidget2.h mydialog.h mainview.h tempview.h .tmp/Third1.0.0/ && $(COPY_FILE) --parents main.cpp mywidget1.cpp mywidget2.cpp mywidget.cpp mydialog.cpp mainview.cpp tempview.cpp .tmp/Third1.0.0/ && (cd `dirname .tmp/Third1.0.0` && $(TAR) Third1.0.0.tar Third1.0.0 && $(COMPRESS) Third1.0.0.tar) && $(MOVE) `dirname .tmp/Third1.0.0`/Third1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Third1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mywidget.cpp moc_mywidget1.cpp moc_mywidget2.cpp moc_mydialog.cpp moc_mainview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mywidget.cpp moc_mywidget1.cpp moc_mywidget2.cpp moc_mydialog.cpp moc_mainview.cpp
moc_mywidget.cpp: mywidget.h
	/opt/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) mywidget.h -o moc_mywidget.cpp

moc_mywidget1.cpp: mywidget1.h
	/opt/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) mywidget1.h -o moc_mywidget1.cpp

moc_mywidget2.cpp: mywidget2.h
	/opt/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) mywidget2.h -o moc_mywidget2.cpp

moc_mydialog.cpp: mydialog.h
	/opt/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) mydialog.h -o moc_mydialog.cpp

moc_mainview.cpp: mainview.h
	/opt/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) mainview.h -o moc_mainview.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp mywidget1.h \
		mywidget2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mywidget1.o: mywidget1.cpp mywidget1.h \
		mydialog.h \
		mainview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mywidget1.o mywidget1.cpp

mywidget2.o: mywidget2.cpp mywidget2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mywidget2.o mywidget2.cpp

mywidget.o: mywidget.cpp mywidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mywidget.o mywidget.cpp

mydialog.o: mydialog.cpp mydialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mydialog.o mydialog.cpp

mainview.o: mainview.cpp mainview.h \
		tempview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainview.o mainview.cpp

tempview.o: tempview.cpp tempview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tempview.o tempview.cpp

moc_mywidget.o: moc_mywidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mywidget.o moc_mywidget.cpp

moc_mywidget1.o: moc_mywidget1.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mywidget1.o moc_mywidget1.cpp

moc_mywidget2.o: moc_mywidget2.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mywidget2.o moc_mywidget2.cpp

moc_mydialog.o: moc_mydialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mydialog.o moc_mydialog.cpp

moc_mainview.o: moc_mainview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainview.o moc_mainview.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

